make:container:
  - App\Ship\Command\CreateContainerCommand
make:controller:
  - App\Ship\Command\CreateControllerCommand
make:model:
  - App\Ship\Command\CreateModelCommand
make:middleware:
  - App\Ship\Command\CreateMiddlewareCommand
make:listener:
  - App\Ship\Command\CreateListenerCommand
make:observer:
  - App\Ship\Command\CreateObserverCommand
make:seed:
  - App\Ship\Command\CreateSeedCommand
make:migration:
  - App\Ship\Command\CreateMigrationCommand
make:interface:
  - App\Ship\Command\CreateInterfaceCommand
make:factory:
  - App\Ship\Command\CreateFactoryCommand

cache:clear:
  - App\Ship\Command\CacheClearCommand

seed:
  - App\Ship\Command\SeedCommand
migrate:
  - App\Ship\Command\MigrateCommand

serve:
  - App\Ship\Command\ServeCommand
run:
  - App\Ship\Command\ServeCommand

help:
  - App\Ship\Command\ConsoleCommand
'' :
  - App\Ship\Command\ConsoleCommand

debug:router:
  - App\Ship\Command\RouterCommand
debug:router:container:
  - App\Ship\Command\RouterCommand
  - actionContainer
debug:listeners:
  - App\Ship\Command\ListenersCommand
debug:observers:
  - App\Ship\Command\ObserversCommand

bcrypt:
  - App\Ship\Command\BcryptCommand

to:yml:
  - App\Ship\Command\ArrayToYml