make:container:
  - App\Ship\Command\MakeContainer
make:controller:
  - App\Ship\Command\MakeController
make:model:
  - App\Ship\Command\MakeModel
make:middleware:
  - App\Ship\Command\MakeMiddleware
make:listener:
  - App\Ship\Command\MakeListener
make:observer:
  - App\Ship\Command\MakeObserver
make:seed:
  - App\Ship\Command\MakeSeed
make:migration:
  - App\Ship\Command\MakeMigration
make:contract:
  - App\Ship\Command\MakeContract
make:factory:
  - App\Ship\Command\MakeFactory

cache:clear:
  - App\Ship\Command\CacheClear

seed:
  - App\Ship\Command\Seed
migrate:
  - App\Ship\Command\Migrate

serve:
  - App\Ship\Command\Serve
run:
  - App\Ship\Command\Serve

help:
  - App\Ship\Command\Help
'' :
  - App\Ship\Command\Help

debug:router:
  - App\Ship\Command\DebugRouter
debug:router:container:
  - App\Ship\Command\DebugRouter
  - actionContainer
debug:listeners:
  - App\Ship\Command\DebugListeners
debug:observers:
  - App\Ship\Command\DebugObservers

bcrypt:
  - App\Ship\Command\Bcrypt

secret:
  - App\Ship\Command\Secret

convert:array-to-yml:
  - App\Ship\Command\ArrayToYml
to:yml:
  - App\Ship\Command\ArrayToYml